In [1]:
b = 32
w1 = 1.8

In [2]:
x1 = 10

y1 = w1*x1 + b
print(y1)

50.0


In [3]:
from torch import tensor

In [5]:
b = tensor(32)
w1 = tensor(1.8)

x1 = tensor([10, 38, 50, 100])

y_pred = 1 * b + w1 * x1
print(y_pred)

tensor([ 50.0000, 100.4000, 122.0000, 212.0000])


In [7]:
print(b.shape)
print(x1.shape)

torch.Size([])
torch.Size([4])


In [8]:
print(b.size())
print(x1.size())

torch.Size([])
torch.Size([4])


In [10]:
print(y_pred[0])
print(y_pred[0].item())

tensor(50.)
50.0


In [14]:
x2 = tensor([[10.0], [39.0], [51.0], [101.0]])
print(x2*w1+b*1)

tensor([[ 50.0000],
        [102.2000],
        [123.8000],
        [213.8000]])


In [19]:
from torch import nn

model = nn.Linear(1,1)
print(model)

Linear(in_features=1, out_features=1, bias=True)


In [22]:
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.2155]], requires_grad=True)
Parameter containing:
tensor([-0.6778], requires_grad=True)


In [23]:
y_pred = model(x2)
print(y_pred)

tensor([[ -2.8326],
        [ -9.0817],
        [-11.6675],
        [-22.4417]], grad_fn=<AddmmBackward0>)


In [26]:
model.bias.item() + 10 * model.weight[0].item()

-2.832643985748291

In [27]:
model.bias = nn.Parameter(tensor([32.0]))

In [28]:
y_pred = model(x2)
print(y_pred)

tensor([[29.8452],
        [23.5961],
        [21.0103],
        [10.2361]], grad_fn=<AddmmBackward0>)


In [29]:
model.weight = nn.Parameter(tensor([[1.8]]))

In [30]:
y_pred = model(x2)
print(y_pred)

tensor([[ 50.0000],
        [102.2000],
        [123.8000],
        [213.8000]], grad_fn=<AddmmBackward0>)


In [35]:
print(type(5.5))
print(type(x2))
print(type(y_pred))
print(type(5))

<class 'float'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'int'>


In [36]:
print(type(4 + 5.5))

<class 'float'>


In [39]:
print(y_pred.dtype)
print(tensor(5).dtype)

torch.float32
torch.int64


In [43]:
from torch import int64, float32
y_pred = y_pred.type(int64)
print(y_pred)

tensor([[ 50],
        [102],
        [123],
        [213]])


In [45]:
y = tensor(34, dtype = float32)
print(y)

tensor(34.)


In [46]:
from torch import nn
x = tensor([[1], [2], [3], [4]], dtype = float32)
model = nn.Linear(1,1)
y_pred2 = model(x)
print(x)
print(y_pred2)
print(model.bias)
print(model.weight)

tensor([[1.],
        [2.],
        [3.],
        [4.]])
tensor([[0.6996],
        [0.7131],
        [0.7267],
        [0.7402]], grad_fn=<AddmmBackward0>)
Parameter containing:
tensor([0.6860], requires_grad=True)
Parameter containing:
tensor([[0.0135]], requires_grad=True)
