In [4]:
import torch
from torch import nn

In [18]:
X1 = torch.tensor([[10.0]], dtype=torch.float32)
y1 = torch.tensor([[50.0]], dtype=torch.float32)

X2 = torch.tensor([[37.78]], dtype=torch.float32)
y2 = torch.tensor(100.0)

model = nn.Linear(1,1)

In [19]:
y1_pred = model(X1)
y2_pred = model(X2)
print(y1_pred)
print(y2_pred)

tensor([[-0.1224]], grad_fn=<AddmmBackward0>)
tensor([[-0.3131]], grad_fn=<AddmmBackward0>)


In [22]:
loss_fn = torch.nn.MSELoss()
print(loss_fn(y1_pred, y1))

print([i for i in model.parameters()])

tensor(2512.2529, grad_fn=<MseLossBackward0>)
[Parameter containing:
tensor([[-0.0069]], requires_grad=True), Parameter containing:
tensor([-0.0537], requires_grad=True)]


In [23]:
optimizer = torch.optim.SGD(model.parameters(), lr = 0.001)

In [24]:
optimizer.zero_grad()
outputs = model(X1)
loss = loss_fn(outputs, y1)
print(loss)

tensor(2512.2529, grad_fn=<MseLossBackward0>)


In [25]:
y1_pred = model(X1)
print(y1_pred)

tensor([[-0.1224]], grad_fn=<AddmmBackward0>)
